POST http://localhost:3003/api/blogs
Content-Type: application/json
 
{
    "title": "Let’s Dive Into Cypress For End-to-End Testing",
    "author": "Ramona Schwering",
    "url": "https://www.smashingmagazine.com/2021/09/cypress-end-to-end-testing/",
    "likes": 25    
}